
2023-08-25 13:28:41,133 Downloading artifact
2023-08-25 13:28:42,940 reading artifact
2023-08-25 13:28:42,995 cleaning artifact
Traceback (most recent call last):
  File "run.py", line 111, in <module>
    go(args)
  File "run.py", line 44, in go
    idx = df['price'].between(args.min_price, args.max_price)
  File "/Users/femibolarinwa_comp/miniconda3/envs/mlflow-14ea07e8e65c1c8b3d59ee64e28b703fc4f03756/lib/python3.8/site-packages/pandas/core/series.py", line 4737, in between
    lmask = self >= left
  File "/Users/femibolarinwa_comp/miniconda3/envs/mlflow-14ea07e8e65c1c8b3d59ee64e28b703fc4f03756/lib/python3.8/site-packages/pandas/core/ops/common.py", line 65, in new_method
    return method(self, other)
  File "/Users/femibolarinwa_comp/miniconda3/envs/mlflow-14ea07e8e65c1c8b3d59ee64e28b703fc4f03756/lib/python3.8/site-packages/pandas/core/arraylike.py", line 49, in __ge__
    return self._cmp_method(other, operator.ge)
  File "/Users/femibolarinwa_comp/miniconda3/envs/mlflow-14ea07e8e65c1c8b3d59ee64e28b703fc4f03756/lib/python3.8/site-packages/pandas/core/series.py", line 4978, in _cmp_method
    res_values = ops.comparison_op(lvalues, rvalues, op)
  File "/Users/femibolarinwa_comp/miniconda3/envs/mlflow-14ea07e8e65c1c8b3d59ee64e28b703fc4f03756/lib/python3.8/site-packages/pandas/core/ops/array_ops.py", line 240, in comparison_op
    return invalid_comparison(lvalues, rvalues, op)
  File "/Users/femibolarinwa_comp/miniconda3/envs/mlflow-14ea07e8e65c1c8b3d59ee64e28b703fc4f03756/lib/python3.8/site-packages/pandas/core/ops/invalid.py", line 34, in invalid_comparison
    raise TypeError(f"Invalid comparison between dtype={left.dtype} and {typ}")
TypeError: Invalid comparison between dtype=int64 and str